"""empty message

Revision ID: 3376fdff6925
Revises: 81e40f002800
Create Date: 2026-04-01 23:21:40.261888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3376fdff6925'
down_revision = '81e40f002800'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remarks', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave', schema=None) as batch_op:
        batch_op.drop_column('remarks')

    # ### end Alembic commands ###
